# CineMatch — Disturbing / Horror Film Scraper
Runs `letterboxd_scraper.py` and shows the output CSVs when done.

In [1]:
%pip install selenium webdriver-manager beautifulsoup4 lxml pandas tqdm

Requirement already satisfied: selenium in /Users/ethan/miniconda3/lib/python3.13/site-packages (4.43.0)
Requirement already satisfied: webdriver-manager in /Users/ethan/miniconda3/lib/python3.13/site-packages (4.0.2)
Requirement already satisfied: beautifulsoup4 in /Users/ethan/miniconda3/lib/python3.13/site-packages (4.14.3)
Requirement already satisfied: lxml in /Users/ethan/miniconda3/lib/python3.13/site-packages (6.1.0)
Requirement already satisfied: pandas in /Users/ethan/miniconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: tqdm in /Users/ethan/miniconda3/lib/python3.13/site-packages (4.67.3)
Requirement already satisfied: certifi>=2026.1.4 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: requests in /Users/ethan/miniconda3/lib/python3.13/site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in /Users/ethan/miniconda3/lib/python3.13/site-packages (from webdriver-manager) (1.2.1)
Requirement already satisfied: packaging in /Users/ethan/miniconda3/lib/python3.13/site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ethan/miniconda3/lib/python3.13/site-packages (from requests->webdriver-manager) (3.4.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%run letterboxd_scraper.py

Starting browser for list collection...

STEP 1: Collecting film URLs from lists

Scraping list: Popular Horror
    [genre] Page 1: 72 items, 72 total
  72 films found

Scraping list: Popular Thriller
  0 films found

Scraping list: Most Disturbing
  0 films found

Scraping list: Horror Essentials
  0 films found

Scraping list: Psychological Horror
  0 films found

Scraping list: Extreme Cinema
  0 films found

disturbing_lists.csv saved -- 72 rows

STEP 2: Scraping 72 unique film pages using 4 browsers in parallel

Films: 100%|██████████| 72/72 [05:20<00:00,  4.45s/it]

disturbing_films.csv saved -- 72 rows

Done. disturbing_films.csv and disturbing_lists.csv are ready to send.

## Preview outputs

In [3]:
import pandas as pd
pd.read_csv("disturbing_films.csv")

,film_title,year,genre,runtime_mins,avg_rating,num_ratings,num_reviews,country,language,letterboxd_url,date_scraped
0,The Exorcist,1973,Horror|Drama,122,3.95,992827,153402,USA,English|German|French|Latin|Arabic|Greek (mode...,https://letterboxd.com/film/the-exorcist/,2026-05-04
1,Carrie,1976,Horror|Thriller,98,3.84,877515,188560,USA,English,https://letterboxd.com/film/carrie-1976/,2026-05-04
2,The Texas Chain Saw Massacre,1974,Horror,83,3.78,911537,224892,USA,English,https://letterboxd.com/film/the-texas-chain-sa...,2026-05-04
3,Saw,2004,Crime|Mystery|Horror,103,3.67,1120881,215138,USA,English,https://letterboxd.com/film/saw/,2026-05-04
4,The Long Walk,2025,Horror|Science Fiction|Thriller,108,3.51,845257,331327,USA,English,https://letterboxd.com/film/the-long-walk-2025/,2026-05-04
...,...,...,...,...,...,...,...,...,...,...,...
67,The Witch,2015,Horror,92,3.82,1458900,247123,Brazil|Canada|UK|USA,English,https://letterboxd.com/film/the-witch-2015/,2026-05-04
68,Split,2016,Horror|Thriller,117,3.52,1806585,164100,USA,English,https://letterboxd.com/film/split-2016/,2026-05-04
69,28 Days Later,2002,Science Fiction|Horror|Thriller,113,3.72,1365023,318907,UK,English|Spanish|English,https://letterboxd.com/film/28-days-later/,2026-05-04
70,28 Years Later,2025,Science Fiction|Thriller|Horror,115,3.44,1281677,468041,UK|USA,English|English|Swedish,https://letterboxd.com/film/28-years-later/,2026-05-04
71,Heretic,2024,Thriller|Horror,111,3.32,1294992,424610,USA,English,https://letterboxd.com/film/heretic-2024/,2026-05-04

In [4]:
import pandas as pd
pd.read_csv("disturbing_films.csv")

,film_title,year,genre,runtime_mins,avg_rating,num_ratings,num_reviews,country,language,letterboxd_url,date_scraped
0,The Exorcist,1973,Horror|Drama,122,3.95,992827,153402,USA,English|German|French|Latin|Arabic|Greek (mode...,https://letterboxd.com/film/the-exorcist/,2026-05-04
1,Carrie,1976,Horror|Thriller,98,3.84,877515,188560,USA,English,https://letterboxd.com/film/carrie-1976/,2026-05-04
2,The Texas Chain Saw Massacre,1974,Horror,83,3.78,911537,224892,USA,English,https://letterboxd.com/film/the-texas-chain-sa...,2026-05-04
3,Saw,2004,Crime|Mystery|Horror,103,3.67,1120881,215138,USA,English,https://letterboxd.com/film/saw/,2026-05-04
4,The Long Walk,2025,Horror|Science Fiction|Thriller,108,3.51,845257,331327,USA,English,https://letterboxd.com/film/the-long-walk-2025/,2026-05-04
...,...,...,...,...,...,...,...,...,...,...,...
67,The Witch,2015,Horror,92,3.82,1458900,247123,Brazil|Canada|UK|USA,English,https://letterboxd.com/film/the-witch-2015/,2026-05-04
68,Split,2016,Horror|Thriller,117,3.52,1806585,164100,USA,English,https://letterboxd.com/film/split-2016/,2026-05-04
69,28 Days Later,2002,Science Fiction|Horror|Thriller,113,3.72,1365023,318907,UK,English|Spanish|English,https://letterboxd.com/film/28-days-later/,2026-05-04
70,28 Years Later,2025,Science Fiction|Thriller|Horror,115,3.44,1281677,468041,UK|USA,English|English|Swedish,https://letterboxd.com/film/28-years-later/,2026-05-04
71,Heretic,2024,Thriller|Horror,111,3.32,1294992,424610,USA,English,https://letterboxd.com/film/heretic-2024/,2026-05-04