# 🎬 Film Scraper — Letterboxd + TMDB

Produces two tidy datasets joinable on `tmdb_id`:
- **`df_lb`** — Letterboxd: ratings, genres, director, cast
- **`df_tmdb`** — TMDB: budget, revenue, runtime, production info

### Setup
```bash
pip install requests beautifulsoup4 lxml python-dateutil tqdm
```
Get a free TMDB API key at [themoviedb.org/settings/api](https://www.themoviedb.org/settings/api)

In [1]:
# !pip install requests beautifulsoup4 lxml python-dateutil tqdm

## 1 · Config

In [6]:
import os

os.environ['TMDB_API_KEY'] = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2YmUzNzUzNGEzMWQ4OGUyZjgwMDgzNTE0ZjIxNTkxNCIsIm5iZiI6MTc3Nzg2NTYyMy41NTIsInN1YiI6IjY5ZjgxMzk3MzJiMjE4YzZlZjIzZTdlMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Ht28-i6lW7eZJu5HF3DiOvoNWd8ImpqEMIjRq6s4UPs'  # paste your key here

# Films to scrape — add/remove as needed
URLS = [
    'https://letterboxd.com/film/the-godfather/',
    'https://letterboxd.com/film/parasite-2019/',
    'https://letterboxd.com/film/seven-samurai/',
    'https://letterboxd.com/film/2001-a-space-odyssey/',
    'https://letterboxd.com/film/mulholland-drive/',
]

LB_OUTPUT   = 'lb_films.json'
TMDB_OUTPUT = 'tmdb_films.json'

## 2 · Imports

In [7]:
import json
import pandas as pd
from film_scraper import scrape_batch, scrape_tmdb_batch, TMDBClient

client = TMDBClient()
print('Ready ✓')

Ready ✓

## 3 · Scrape Letterboxd

In [4]:
lb_films = scrape_batch(URLS, delay_range=(2, 4), output_file=LB_OUTPUT)
df_lb = pd.DataFrame([f.to_dict() for f in lb_films])
df_lb

Letterboxd: 100%|███████████████████████████████████████████████| 5/5 [00:02<00:00,  1.84film/s, film=Mulholland Drive]

,movie_id,name,url,lid,tmdb_id,number_of_ratings,avg_rating,genres,director_url,actors_urls
0,1,The Godfather,/film/the-godfather/,51818,238,2651905,4.52,"[crime, drama]",/director/francis-ford-coppola/,"[/actor/marlon-brando/, /actor/al-pacino/, /ac..."
1,2,Parasite,/film/parasite-2019/,426406,496243,5323651,4.53,"[thriller, comedy, drama]",/director/bong-joon-ho/,"[/actor/song-kang-ho/, /actor/lee-sun-kyun/, /..."
2,3,Seven Samurai,/film/seven-samurai/,51716,346,429806,4.60,"[action, drama]",/director/akira-kurosawa/,"[/actor/toshiro-mifune/, /actor/takashi-shimur..."
3,4,2001: A Space Odyssey,/film/2001-a-space-odyssey/,51987,62,1457452,4.25,"[science fiction, adventure, mystery]",/director/stanley-kubrick/,"[/actor/keir-dullea/, /actor/gary-lockwood/, /..."
4,5,Mulholland Drive,/film/mulholland-drive/,51171,1018,1232409,4.26,"[drama, mystery, thriller]",/director/david-lynch/,"[/actor/naomi-watts/, /actor/laura-harring/, /..."

## 4 · Scrape TMDB
TMDB IDs are extracted automatically from the Letterboxd pages.

In [5]:
tmdb_ids = [f.tmdb_id for f in lb_films if f.tmdb_id]
tmdb_films = scrape_tmdb_batch(tmdb_ids, client=client, output_file=TMDB_OUTPUT)
df_tmdb = pd.DataFrame([f.to_dict() for f in tmdb_films])
df_tmdb

TMDB: 100%|█████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.02film/s, film=Mulholland Drive]

,movie_id,release_decade,production_companies,production_countries,revenue,profit,movie_age,release_date,budget,name,tmdb_id,release_year,production_country_group,runtime,in_franchise,belongs_to_collection,original_language
0,1,1970,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",[united states of america],245066411,239066411,54,1972-03-14,6000000,The Godfather,238,1972,[North America],175,True,"{'name': 'The Godfather Collection', 'id': 230}",en
1,2,2010,"[{'name': 'Barunson E&A', 'id': 4399}]",[south korea],257591776,246228776,7,2019-05-30,11363000,Parasite,496243,2019,[Asia],133,False,NaN,ko
2,3,1950,"[{'name': 'TOHO', 'id': 882}]",[japan],105000000,103000000,72,1954-04-26,2000000,Seven Samurai,346,1954,[Asia],207,False,NaN,ja
3,4,1960,"[{'name': 'Stanley Kubrick Productions', 'id':...","[united kingdom, united states of america]",71923560,59923560,58,1968-04-02,12000000,2001: A Space Odyssey,62,1968,"[North America, Europe]",149,True,"{'name': 'The Space Odyssey Series', 'id': 4438}",en
4,5,2000,"[{'name': 'StudioCanal', 'id': 694}, {'name': ...","[france, united states of america]",20289986,5289986,25,2001-06-06,15000000,Mulholland Drive,1018,2001,"[North America, Europe]",147,False,NaN,en

## 5 · Join both datasets

In [6]:
df = df_lb.merge(df_tmdb, on='tmdb_id', suffixes=('_lb', '_tmdb'))

# Resolve duplicate columns — prefer Letterboxd name and movie_id
for col in ['name', 'movie_id']:
    if f'{col}_lb' in df.columns:
        df = df.rename(columns={f'{col}_lb': col})
        df = df.drop(columns=[f'{col}_tmdb'], errors='ignore')

df

,movie_id,name,url,lid,tmdb_id,number_of_ratings,avg_rating,genres,director_url,actors_urls,...,profit,movie_age,release_date,budget,release_year,production_country_group,runtime,in_franchise,belongs_to_collection,original_language
0,1,The Godfather,/film/the-godfather/,51818,238,2651905,4.52,"[crime, drama]",/director/francis-ford-coppola/,"[/actor/marlon-brando/, /actor/al-pacino/, /ac...",...,239066411,54,1972-03-14,6000000,1972,[North America],175,True,"{'name': 'The Godfather Collection', 'id': 230}",en
1,2,Parasite,/film/parasite-2019/,426406,496243,5323651,4.53,"[thriller, comedy, drama]",/director/bong-joon-ho/,"[/actor/song-kang-ho/, /actor/lee-sun-kyun/, /...",...,246228776,7,2019-05-30,11363000,2019,[Asia],133,False,NaN,ko
2,3,Seven Samurai,/film/seven-samurai/,51716,346,429806,4.60,"[action, drama]",/director/akira-kurosawa/,"[/actor/toshiro-mifune/, /actor/takashi-shimur...",...,103000000,72,1954-04-26,2000000,1954,[Asia],207,False,NaN,ja
3,4,2001: A Space Odyssey,/film/2001-a-space-odyssey/,51987,62,1457452,4.25,"[science fiction, adventure, mystery]",/director/stanley-kubrick/,"[/actor/keir-dullea/, /actor/gary-lockwood/, /...",...,59923560,58,1968-04-02,12000000,1968,"[North America, Europe]",149,True,"{'name': 'The Space Odyssey Series', 'id': 4438}",en
4,5,Mulholland Drive,/film/mulholland-drive/,51171,1018,1232409,4.26,"[drama, mystery, thriller]",/director/david-lynch/,"[/actor/naomi-watts/, /actor/laura-harring/, /...",...,5289986,25,2001-06-06,15000000,2001,"[North America, Europe]",147,False,NaN,en

## 6 · Schema reference

### Letterboxd (`df_lb`)
| Column | Description |
|---|---|
| `movie_id` | 1-based scrape index |
| `name` | Film title |
| `url` | Letterboxd path, e.g. `/film/the-godfather/` |
| `lid` | Letterboxd internal film ID |
| `tmdb_id` | TMDB movie ID (join key) |
| `number_of_ratings` | Total ratings count |
| `avg_rating` | Average rating out of 5 |
| `genres` | List of genre strings |
| `director_url` | Letterboxd creator URL |
| `actors_urls` | List of Letterboxd creator URLs |

### TMDB (`df_tmdb`)
| Column | Description |
|---|---|
| `tmdb_id` | TMDB movie ID (join key) |
| `name` | TMDB title |
| `release_date` / `release_year` / `release_decade` | Release info |
| `movie_age` | Years since release |
| `runtime` | Runtime in minutes |
| `budget` / `revenue` / `profit` | Box office (USD) |
| `original_language` | ISO 639-1 language code |
| `in_franchise` | Part of a collection? |
| `belongs_to_collection` | `{name, id}` if in a franchise |
| `production_companies` | `[{name, id}, ...]` |
| `production_countries` | Lowercase country names |
| `production_country_group` | Continents derived from countries |

## 7 · Scrape a single film

In [7]:
# from film_scraper import scrape_film, scrape_tmdb
# import pprint

# film = scrape_film('https://letterboxd.com/film/the-godfather/')
# pprint.pprint(film.to_dict())

In [8]:
tmdb = scrape_tmdb(film.tmdb_id, client)
pprint.pprint(tmdb.to_dict())

NameError: name 'scrape_tmdb' is not defined

## 8 · Reload from saved JSON

In [ ]:
with open(LB_OUTPUT) as f:
    df_lb_saved = pd.DataFrame(json.load(f))

with open(TMDB_OUTPUT) as f:
    df_tmdb_saved = pd.DataFrame(json.load(f))

print('lb:', df_lb_saved.shape, '| tmdb:', df_tmdb_saved.shape)
df_lb_saved.head()

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from film_scraper import scrape_film, FilmData
import os
import pandas as pd

path = os.path.join('..', 'Data Scrapping RESULTS', 'user_ratings.csv')
df_ratings = pd.read_csv(path)
urls = df_ratings.film_slug.unique()
links = ['https://letterboxd.com/film/' + film + '/' for film in urls]

MAX_WORKERS = 10
results = [None] * len(links)

with tqdm(total=len(links), desc='Letterboxd', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {executor.submit(scrape_film, url): i for i, url in enumerate(links)}
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                film = future.result()
                film.movie_id = i + 1
                results[i] = film
                bar.set_postfix(film=film.name or links[i], refresh=True)
            except Exception as exc:
                results[i] = FilmData(movie_id=i + 1)
                tqdm.write(f'Failed: {links[i]} — {exc}')
            bar.update(1)

lb_data = pd.DataFrame([f.to_dict() for f in results if f])
lb_data

In [ ]:
lb_data.to_csv('lb_data_detailed.csv')

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

tmdb_ids = [f.tmdb_id for f in lb_films if f.tmdb_id]

MAX_WORKERS = 10
tmdb_results = [None] * len(tmdb_ids)

with tqdm(total=len(tmdb_ids), desc='TMDB', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {
            executor.submit(client.get_film, tmdb_id): i
            for i, tmdb_id in enumerate(tmdb_ids)
        }
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                film = future.result()
                tmdb_results[i] = film
                bar.set_postfix(id=tmdb_ids[i], refresh=True)
            except Exception as exc:
                tmdb_results[i] = None
                tqdm.write(f'Failed: {tmdb_ids[i]} — {exc}')
            bar.update(1)

tmdb_films = [f for f in tmdb_results if f]
df_tmdb = pd.DataFrame([f.to_dict() for f in tmdb_films])
df_tmdb

In [ ]:
lb_data = pd.read_csv('lb_data_detailed.csv')
lb_data.tmdb_id

In [ ]:
links.append('https://letterboxd.com/film/ellen/')

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from film_scraper import scrape_film, FilmData
import os
import pandas as pd

path = os.path.join('..', 'Data Scrapping RESULTS', 'user_ratings.csv')
df_ratings = pd.read_csv(path)
urls = df_ratings.film_slug.unique()
links = ['https://letterboxd.com/film/' + film + '/' for film in urls]

# Load already-scraped slugs from the output file
OUTPUT_FILE = 'lb_data_detailed.csv'
if os.path.exists(OUTPUT_FILE):
    existing_df = pd.read_csv(OUTPUT_FILE)
    scraped_slugs = set(existing_df['url'].str.strip('/').str.split('/').str[-1])
else:
    existing_df = pd.DataFrame()
    scraped_slugs = set()

# Filter to only unscraped links
pending = [(i, url) for i, url in enumerate(links)
           if url.strip('/').split('/')[-1] not in scraped_slugs]
print(f"Total: {len(links)} | Already done: {len(links) - len(pending)} | Remaining: {len(pending)}")

MAX_WORKERS = 10
results = [None] * len(links)

with tqdm(total=len(pending), desc='Letterboxd', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {executor.submit(scrape_film, url): i for i, url in pending}
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                film = future.result()
                film.movie_id = i + 1
                results[i] = film
                bar.set_postfix(film=film.name or links[i], refresh=True)
            except Exception as exc:
                results[i] = FilmData(movie_id=i + 1)
                tqdm.write(f'Failed: {links[i]} — {exc}')
            bar.update(1)

# Combine new results with existing data
new_df = pd.DataFrame([f.to_dict() for f in results if f])
lb_data = pd.concat([existing_df, new_df], ignore_index=True).drop_duplicates(subset='url')
lb_data

In [8]:
import os
import pandas as pd

output_dir = os.path.join('..', '..', 'geoff run')

dfs = []
for i in range(1, 9):
    fpath = os.path.join(output_dir, f'output_{i}.csv')
    if os.path.exists(fpath):
        dfs.append(pd.read_csv(fpath))
    else:
        print(f'Not found, skipping: output_{i}.csv')
user_data = pd.concat(dfs, ignore_index=True).drop_duplicates(subset='movie_title')

In [9]:
user_data['tmdb_id'] = pd.to_numeric(user_data['tmdb_id'], errors='coerce').astype('Int64')
user_data.tmdb_id.unique()
# user_data

<IntegerArray>
[1226863, 1493859,  687163, 1650397, 1327819, 1617908, 1548113,    <NA>,
 1272837, 1499744,
 ...
  371129, 1045849, 1045874,  332264,  102284,  583725,  577413,  456026,
  757289,  590867]
Length: 292701, dtype: Int64

In [33]:
from film_scraper import scrape_tmdb, TMDBClient, _SESSION
from requests.adapters import HTTPAdapter
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

logging.getLogger("urllib3").setLevel(logging.ERROR)
logging.getLogger("film_scraper").setLevel(logging.ERROR)

MAX_WORKERS = 80

tmdb_ids = [str(int(f)) for f in user_data.tmdb_id.dropna().unique()]

adapter = HTTPAdapter(pool_connections=MAX_WORKERS, pool_maxsize=MAX_WORKERS)
_SESSION.mount("https://", adapter)
_SESSION.mount("http://", adapter)

client = TMDBClient()  # recreate AFTER mounting adapter

tmdb_results = [None] * len(tmdb_ids)
failed_ids = []

with tqdm(total=len(tmdb_ids), desc='TMDB', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {
            executor.submit(scrape_tmdb, tmdb_id, client): i
            for i, tmdb_id in enumerate(tmdb_ids)
        }
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                film = future.result()
                film.movie_id = i + 1
                tmdb_results[i] = film
            except Exception as e:
                failed_ids.append((tmdb_ids[i], str(e)))  # temporarily store error too
            bar.update(1)

df_tmdb = pd.DataFrame([f.to_dict() for f in tmdb_results if f])
print(f"Done. {len(df_tmdb)} films collected, {len(failed_ids)} failed.")
if failed_ids:
    print("First 3 errors:", failed_ids[:3])  # see what's actually going wrong

TMDB: 100%|████████████████████████████████████████████████████████████████| 292700/292700 [1:07:53<00:00, 71.85film/s]

Done. 285459 films collected, 7241 failed.
First 3 errors: [('1326824', 'TMDB returned nothing for ID 1326824'), ('1111773', 'TMDB returned nothing for ID 1111773'), ('689588', 'TMDB returned nothing for ID 689588')]

In [36]:
df_tmdb

,movie_id,release_decade,production_companies,production_countries,revenue,profit,movie_age,release_date,budget,name,tmdb_id,release_year,production_country_group,runtime,in_franchise,belongs_to_collection,original_language
0,1,2020.0,"[{'name': 'Illumination', 'id': 6704}, {'name'...","[japan, united states of america]",894200000.0,784200000.0,0.0,2026-04-01,110000000.0,The Super Mario Galaxy Movie,1226863,2026.0,"[North America, Asia]",98.0,True,"{'name': 'The Super Mario Collection', 'id': 1...",en
1,2,2020.0,"[{'name': 'American High', 'id': 112397}, {'na...",[united states of america],NaN,NaN,0.0,2026-03-13,NaN,Pizza Movie,1493859,2026.0,[North America],98.0,False,NaN,en
2,3,2020.0,"[{'name': 'Lord Miller', 'id': 77973}, {'name'...",[united states of america],638443000.0,438443000.0,0.0,2026-03-15,200000000.0,Project Hail Mary,687163,2026.0,[North America],157.0,False,NaN,en
3,4,2020.0,NaN,[united states of america],NaN,NaN,0.0,2026-02-28,NaN,The Match-Stick Flame 3: Red Mafia,1650397,2026.0,[North America],69.0,False,NaN,en
4,5,2020.0,"[{'name': 'Pixar', 'id': 3}]",[united states of america],371329450.0,221329450.0,0.0,2026-03-04,150000000.0,Hoppers,1327819,2026.0,[North America],105.0,False,NaN,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285454,292696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,How to Answer the Fool,583725,NaN,NaN,85.0,False,NaN,en
285455,292697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ghost Stories: The Curious Tales of the Making...,577413,NaN,NaN,72.0,False,NaN,en
285456,292698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phantasmagorical Mystery Tour,456026,NaN,NaN,16.0,False,NaN,en
285457,292699,NaN,"[{'name': 'Boll KG', 'id': 15127}]","[canada, germany, united states of america]",NaN,NaN,NaN,NaN,NaN,Rampage IV: The New Blood,757289,NaN,"[North America, Europe]",NaN,True,"{'name': 'Rampage Collection', 'id': 283417}",en
285458,292700,NaN,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",[united states of america],NaN,NaN,NaN,NaN,NaN,Hunchback,590867,NaN,[North America],NaN,False,NaN,en

In [10]:
df_tmdb = pd.read_csv('tmdb_data_detailed.csv')
df_tmdb

,Unnamed: 0,movie_id,release_decade,production_companies,production_countries,revenue,profit,movie_age,release_date,budget,name,tmdb_id,release_year,production_country_group,runtime,in_franchise,belongs_to_collection,original_language
0,0,1,2020.0,"[{'name': 'Illumination', 'id': 6704}, {'name'...","['japan', 'united states of america']",894200000.0,784200000.0,0.0,2026-04-01,110000000.0,The Super Mario Galaxy Movie,1226863,2026.0,"['North America', 'Asia']",98.0,True,"{'name': 'The Super Mario Collection', 'id': 1...",en
1,1,2,2020.0,"[{'name': 'American High', 'id': 112397}, {'na...",['united states of america'],NaN,NaN,0.0,2026-03-13,NaN,Pizza Movie,1493859,2026.0,['North America'],98.0,False,NaN,en
2,2,3,2020.0,"[{'name': 'Lord Miller', 'id': 77973}, {'name'...",['united states of america'],638443000.0,438443000.0,0.0,2026-03-15,200000000.0,Project Hail Mary,687163,2026.0,['North America'],157.0,False,NaN,en
3,3,4,2020.0,NaN,['united states of america'],NaN,NaN,0.0,2026-02-28,NaN,The Match-Stick Flame 3: Red Mafia,1650397,2026.0,['North America'],69.0,False,NaN,en
4,4,5,2020.0,"[{'name': 'Pixar', 'id': 3}]",['united states of america'],371329450.0,221329450.0,0.0,2026-03-04,150000000.0,Hoppers,1327819,2026.0,['North America'],105.0,False,NaN,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285454,285454,292696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,How to Answer the Fool,583725,NaN,NaN,85.0,False,NaN,en
285455,285455,292697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ghost Stories: The Curious Tales of the Making...,577413,NaN,NaN,72.0,False,NaN,en
285456,285456,292698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phantasmagorical Mystery Tour,456026,NaN,NaN,16.0,False,NaN,en
285457,285457,292699,NaN,"[{'name': 'Boll KG', 'id': 15127}]","['canada', 'germany', 'united states of america']",NaN,NaN,NaN,NaN,NaN,Rampage IV: The New Blood,757289,NaN,"['North America', 'Europe']",NaN,True,"{'name': 'Rampage Collection', 'id': 283417}",en
285458,285458,292700,NaN,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",['united states of america'],NaN,NaN,NaN,NaN,NaN,Hunchback,590867,NaN,['North America'],NaN,False,NaN,en

In [15]:
import os
import logging
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from requests.adapters import HTTPAdapter
from film_scraper import TMDBClient, _SESSION

logging.getLogger("urllib3").setLevel(logging.ERROR)
logging.getLogger("film_scraper").setLevel(logging.ERROR)

MAX_WORKERS = 80

# ── Fix connection pool ───────────────────────────────────────────────────
adapter = HTTPAdapter(pool_connections=MAX_WORKERS, pool_maxsize=MAX_WORKERS)
_SESSION.mount("https://", adapter)
_SESSION.mount("http://", adapter)
client = TMDBClient()

MAJOR_STUDIOS = {
    "Warner Bros", "Universal", "Paramount", "Walt Disney",
    "Sony", "20th Century", "Lionsgate", "MGM", "Miramax",
    "Netflix", "Amazon", "Apple", "Hulu", "HBO"
}

def get_film_features(tmdb_id: str, client: TMDBClient, country: str = "US") -> dict:
    """
    Fetch enriched film features from TMDB in a single API call via
    append_to_response, plus a second call for director filmography.
    """
    data = client.get(
        f"movie/{tmdb_id}",
        append_to_response="credits,keywords,release_dates,external_ids"
    )
    if not data:
        return {"tmdb_id": tmdb_id}

    result = {"tmdb_id": tmdb_id}

    # ── Base film fields ──────────────────────────────────────────────────
    result["budget"]            = data.get("budget") or None
    result["revenue"]           = data.get("revenue") or None
    result["runtime"]           = data.get("runtime") or None
    result["original_language"] = data.get("original_language")
    result["in_franchise"]      = data.get("belongs_to_collection") is not None
    result["vote_average"]      = data.get("vote_average")
    result["vote_count"]        = data.get("vote_count")
    result["popularity"]        = data.get("popularity")

    release_date = data.get("release_date", "")
    if release_date:
        result["release_year"]  = int(release_date[:4])
        result["release_month"] = int(release_date[5:7])  # seasonality signal
    else:
        result["release_year"]  = None
        result["release_month"] = None

    # ── Release type ──────────────────────────────────────────────────────
    release_type = None
    for entry in data.get("release_dates", {}).get("results", []):
        if entry["iso_3166_1"] == country:
            types = {r["type"] for r in entry["release_dates"]}
            if 3 in types or 2 in types:
                release_type = "theatrical"
            elif 6 in types or 4 in types:
                release_type = "streaming"
            break
    result["release_type"] = release_type

    # ── Production ────────────────────────────────────────────────────────
    companies = data.get("production_companies", [])
    company_names = [c["name"] for c in companies if c.get("name")]
    result["production_company_count"] = len(company_names)
    result["is_major_studio"] = any(
        any(studio in name for studio in MAJOR_STUDIOS)
        for name in company_names
    )

    countries = data.get("production_countries", [])
    result["is_us_production"]  = any(c["iso_3166_1"] == "US" for c in countries)
    result["n_production_countries"] = len(countries)

    # ── External IDs — social media presence ─────────────────────────────
    ext = data.get("external_ids", {})
    result["has_imdb"]      = bool(ext.get("imdb_id"))
    result["has_facebook"]  = bool(ext.get("facebook_id"))
    result["has_instagram"] = bool(ext.get("instagram_id"))
    result["has_twitter"]   = bool(ext.get("twitter_id"))
    result["social_media_count"] = sum([
        result["has_facebook"], result["has_instagram"], result["has_twitter"]
    ])

    # ── Credits ───────────────────────────────────────────────────────────
    credits = data.get("credits", {})
    cast = sorted(credits.get("cast", []), key=lambda x: x.get("order", 999))
    result["cast_size"] = len(cast)
    for i, actor in enumerate(cast[:3]):
        result[f"cast_{i+1}_popularity"] = actor.get("popularity")

    crew = credits.get("crew", [])
    directors = [c for c in crew if c.get("job") == "Director"]
    director_id = directors[0].get("id") if directors else None
    result["director_popularity"] = directors[0].get("popularity") if directors else None
    result["director_name"]       = directors[0].get("name") if directors else None

    producers = [c for c in crew if c.get("job") in ("Producer", "Executive Producer")]
    result["producer_count"] = len(producers)

    # ── Director prior films (second API call) ────────────────────────────
    result["director_prior_films"] = None
    if director_id:
        person_data = client.get(f"person/{director_id}/movie_credits")
        if person_data:
            directed = [
                c for c in person_data.get("crew", [])
                if c.get("job") == "Director"
                and str(c.get("id")) != str(tmdb_id)
            ]
            result["director_prior_films"] = len(directed)

    # ── Keywords ──────────────────────────────────────────────────────────
    keywords = [kw["name"] for kw in data.get("keywords", {}).get("keywords", [])]
    result["keywords"]      = keywords
    result["keyword_count"] = len(keywords)

    signal_keywords = {
        "independent film", "direct-to-video", "based on novel",
        "sequel", "superhero", "remake", "based on true story",
        "documentary", "animation"
    }
    for kw in signal_keywords:
        result[f"kw_{kw.replace(' ', '_')}"] = kw in keywords

    # ── Engineered features ───────────────────────────────────────────────
    # Star power — weighted popularity of top 3 cast
    c1 = result.get("cast_1_popularity") or 0
    c2 = result.get("cast_2_popularity") or 0
    c3 = result.get("cast_3_popularity") or 0
    result["star_power"] = round(c1 * 0.5 + c2 * 0.3 + c3 * 0.2, 4)

    # Budget per minute — production ambition proxy
    if result["budget"] and result["runtime"]:
        result["budget_per_min"] = round(result["budget"] / result["runtime"], 2)
    else:
        result["budget_per_min"] = None

    # Profit margin — only meaningful when both are non-zero
    if result["budget"] and result["revenue"]:
        result["profit"]        = result["revenue"] - result["budget"]
        result["profit_margin"] = round(result["profit"] / result["budget"], 4)
    else:
        result["profit"]        = None
        result["profit_margin"] = None

    return result


# ── Parallelized fetch ────────────────────────────────────────────────────
tmdb_ids = [str(int(f)) for f in user_data.tmdb_id.dropna().unique()]

film_features = [None] * len(tmdb_ids)
failed_features = []

with tqdm(total=len(tmdb_ids), desc='TMDB enriched', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {
            executor.submit(get_film_features, tmdb_id, client): i
            for i, tmdb_id in enumerate(tmdb_ids)
        }
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                film_features[i] = future.result()
            except Exception as e:
                failed_features.append((tmdb_ids[i], str(e)))
                film_features[i] = {"tmdb_id": tmdb_ids[i]}
            bar.update(1)

df_features = pd.DataFrame([f for f in film_features if f])
print(f"Done. {len(df_features)} films, {len(failed_features)} failed.")
if failed_features:
    print("First 3 errors:", failed_features[:3])
print(f"\nRelease type breakdown:\n{df_features['release_type'].value_counts(dropna=False)}")
df_features

TMDB enriched: 100%|███████████████████████████████████████████████████████| 292700/292700 [2:39:05<00:00, 30.66film/s]

Done. 292700 films, 0 failed.

Release type breakdown:
release_type
None          161642
theatrical     93060
streaming      29193
NaN             8805
Name: count, dtype: int64

,tmdb_id,budget,revenue,runtime,original_language,in_franchise,vote_average,vote_count,popularity,release_year,...,kw_remake,kw_based_on_true_story,kw_sequel,kw_based_on_novel,kw_documentary,kw_direct-to-video,star_power,budget_per_min,profit,profit_margin
0,1226863,110000000.0,894200000.0,98.0,en,True,6.749,727.0,476.4861,2026.0,...,False,False,True,False,False,False,5.8011,1122448.98,784200000.0,7.1291
1,1493859,NaN,NaN,98.0,en,False,6.378,94.0,10.6459,2026.0,...,False,False,False,False,False,False,2.3451,NaN,NaN,NaN
2,687163,200000000.0,638443000.0,157.0,en,False,8.209,1926.0,131.7927,2026.0,...,False,False,False,False,False,False,6.6516,1273885.35,438443000.0,2.1922
3,1650397,NaN,NaN,69.0,en,False,0.000,0.0,0.4409,2026.0,...,False,False,False,False,False,False,0.0898,NaN,NaN,NaN
4,1327819,150000000.0,371329450.0,105.0,en,False,7.746,731.0,193.6600,2026.0,...,False,False,False,False,False,False,2.5944,1428571.43,221329450.0,1.4755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292695,583725,NaN,NaN,85.0,en,False,0.000,0.0,0.0143,NaN,...,False,False,False,False,False,False,0.0206,NaN,NaN,NaN
292696,577413,NaN,NaN,72.0,en,False,0.000,0.0,0.0493,NaN,...,False,False,False,False,False,False,0.4240,NaN,NaN,NaN
292697,456026,NaN,NaN,16.0,en,False,8.000,1.0,0.0661,NaN,...,False,False,False,False,False,False,0.3213,NaN,NaN,NaN
292698,757289,NaN,NaN,NaN,en,True,0.000,0.0,0.2530,NaN,...,False,False,False,False,False,False,0.9515,NaN,NaN,NaN
292699,590867,NaN,NaN,NaN,en,False,0.000,0.0,0.8671,NaN,...,False,False,False,False,False,False,0.0000,NaN,NaN,NaN

In [17]:
df_features.to_csv('tmdb_features.csv')

In [31]:
def get_new_features(tmdb_id: str, client: TMDBClient) -> dict:
    data = client.get(
        f"movie/{tmdb_id}",
        append_to_response="credits"
    )
    if not data:
        return {"tmdb_id": tmdb_id}

    credits = data.get("credits", {})
    cast = sorted(credits.get("cast", []), key=lambda x: x.get("order", 999))

    return {
        "tmdb_id":          tmdb_id,
        "tagline":          data.get("tagline") or None,
        "overview":         data.get("overview") or None,
        "spoken_languages": [l["iso_639_1"] for l in data.get("spoken_languages", []) if l.get("iso_639_1")],
        "full_cast":        [
            {
                "id":         a.get("id"),
                "name":       a.get("name"),
                "character":  a.get("character"),
                "popularity": a.get("popularity"),
                "order":      a.get("order"),
            }
            for a in cast
        ],
    }


tmdb_ids = [str(int(f)) for f in user_data.tmdb_id.dropna().unique()]
new_features = [None] * len(tmdb_ids)
failed_new = []

with tqdm(total=len(tmdb_ids), desc='TMDB new features', unit='film') as bar:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {
            executor.submit(get_new_features, tmdb_id, client): i
            for i, tmdb_id in enumerate(tmdb_ids)
        }
        for future in as_completed(future_to_idx):
            i = future_to_idx[future]
            try:
                new_features[i] = future.result()
            except Exception as e:
                failed_new.append((tmdb_ids[i], str(e)))
            bar.update(1)

df_new = pd.DataFrame([f for f in new_features if f])
print(f"Done. {len(df_new)} films, {len(failed_new)} failed.")
df_new

TMDB new features: 100%|███████████████████████████████████████████████████| 292700/292700 [1:00:26<00:00, 80.70film/s]

Done. 292700 films, 0 failed.

,tmdb_id,tagline,overview,spoken_languages,full_cast
0,1226863,The galaxy awaits.,Having thwarted Bowser's previous plot to marr...,[en],"[{'id': 73457, 'name': 'Chris Pratt', 'charact..."
1,1493859,College is a trip.,A group of college students go downstairs to t...,[en],"[{'id': 1653291, 'name': 'Gaten Matarazzo', 'c..."
2,687163,Believe in the Hail Mary.,Science teacher Ryland Grace wakes up on a spa...,"[en, zh, ru]","[{'id': 30614, 'name': 'Ryan Gosling', 'charac..."
3,1650397,None,"Dalton, who's now a bounty hunter, finishes hi...",[en],"[{'id': 1379504, 'name': 'Craig Robert Bruss',..."
4,1327819,Act natural.,Scientists have discovered how to 'hop' human ...,"[en, es]","[{'id': 1308818, 'name': 'Piper Curda', 'chara..."
...,...,...,...,...,...
292695,583725,A Presuppositional Defense of the Faith,"Produced as a cinematic film, How to Answer th...",[],"[{'id': 2246791, 'name': 'Sye Ten Bruggencate'..."
292696,577413,None,An all-new 72 minute featurette including inte...,[],"[{'id': 1173259, 'name': 'Kim Newman', 'charac..."
292697,456026,None,Phantasmagorical Mystery Tour – location tour ...,[],"[{'id': 97939, 'name': 'Reggie Bannister', 'ch..."
292698,757289,None,The fourth film in the Bill Williamson saga.,[en],"[{'id': 32205, 'name': 'Brendan Fletcher', 'ch..."
292699,590867,None,Live-action adaptation of Disney's animated mu...,[en],[]

In [33]:
df_new.head()

,tmdb_id,tagline,overview,spoken_languages,full_cast
0,1226863,The galaxy awaits.,Having thwarted Bowser's previous plot to marr...,[en],"[{'id': 73457, 'name': 'Chris Pratt', 'charact..."
1,1493859,College is a trip.,A group of college students go downstairs to t...,[en],"[{'id': 1653291, 'name': 'Gaten Matarazzo', 'c..."
2,687163,Believe in the Hail Mary.,Science teacher Ryland Grace wakes up on a spa...,"[en, zh, ru]","[{'id': 30614, 'name': 'Ryan Gosling', 'charac..."
3,1650397,None,"Dalton, who's now a bounty hunter, finishes hi...",[en],"[{'id': 1379504, 'name': 'Craig Robert Bruss',..."
4,1327819,Act natural.,Scientists have discovered how to 'hop' human ...,"[en, es]","[{'id': 1308818, 'name': 'Piper Curda', 'chara..."

In [34]:
df_tmdb1

,Unnamed: 0,movie_id,release_decade,production_companies,production_countries,revenue,profit,movie_age,release_date,budget,name,tmdb_id,release_year,production_country_group,runtime,in_franchise,belongs_to_collection,original_language
0,0,1,2020.0,"[{'name': 'Illumination', 'id': 6704}, {'name'...","['japan', 'united states of america']",894200000.0,784200000.0,0.0,2026-04-01,110000000.0,The Super Mario Galaxy Movie,1226863,2026.0,"['North America', 'Asia']",98.0,True,"{'name': 'The Super Mario Collection', 'id': 1...",en
1,1,2,2020.0,"[{'name': 'American High', 'id': 112397}, {'na...",['united states of america'],NaN,NaN,0.0,2026-03-13,NaN,Pizza Movie,1493859,2026.0,['North America'],98.0,False,NaN,en
2,2,3,2020.0,"[{'name': 'Lord Miller', 'id': 77973}, {'name'...",['united states of america'],638443000.0,438443000.0,0.0,2026-03-15,200000000.0,Project Hail Mary,687163,2026.0,['North America'],157.0,False,NaN,en
3,3,4,2020.0,NaN,['united states of america'],NaN,NaN,0.0,2026-02-28,NaN,The Match-Stick Flame 3: Red Mafia,1650397,2026.0,['North America'],69.0,False,NaN,en
4,4,5,2020.0,"[{'name': 'Pixar', 'id': 3}]",['united states of america'],371329450.0,221329450.0,0.0,2026-03-04,150000000.0,Hoppers,1327819,2026.0,['North America'],105.0,False,NaN,en

In [38]:
df_merged = df_merged.merge(
    df_new.assign(tmdb_id=df_new['tmdb_id'].astype('int64')),
    on='tmdb_id',
    how='inner'
)
df_merged.to_csv('tmdb_data_final.csv')

In [39]:
import math

def split_df_to_csvs(df: pd.DataFrame, max_mb: float, base_name: str) -> list[str]:
    """
    Splits a DataFrame into multiple CSVs, each under max_mb megabytes.
    Returns a list of filenames written.
    """
    max_bytes = max_mb * 1024 * 1024

    # Estimate rows per chunk based on a sample
    sample = df.iloc[:min(100, len(df))].to_csv(index=False).encode()
    bytes_per_row = len(sample) / min(100, len(df))
    rows_per_chunk = max(1, math.floor(max_bytes / bytes_per_row))

    filenames = []
    n_chunks = math.ceil(len(df) / rows_per_chunk)

    for i in range(n_chunks):
        chunk = df.iloc[i * rows_per_chunk : (i + 1) * rows_per_chunk]
        fname = f"{base_name}_{i+1}_of_{n_chunks}.csv"
        chunk.to_csv(fname, index=False)
        filenames.append(fname)
        print(f"  Written: {fname} ({len(chunk)} rows)")

    return filenames


# Usage:
# split_df_to_csvs(df_new, max_mb=50, base_name="tmdb_new_features")

In [44]:
df_merged

,movie_id,release_decade,production_companies,production_countries,revenue_x,profit_x,movie_age,release_date,budget_x,name,...,profit_y,profit_margin,tagline_x,overview_x,spoken_languages_x,full_cast_x,tagline_y,overview_y,spoken_languages_y,full_cast_y
0,1,2020.0,"[{'name': 'Illumination', 'id': 6704}, {'name'...","['japan', 'united states of america']",894200000.0,784200000.0,0.0,2026-04-01,110000000.0,The Super Mario Galaxy Movie,...,784200000.0,7.1291,The galaxy awaits.,Having thwarted Bowser's previous plot to marr...,[en],"[{'id': 73457, 'name': 'Chris Pratt', 'charact...",The galaxy awaits.,Having thwarted Bowser's previous plot to marr...,[en],"[{'id': 73457, 'name': 'Chris Pratt', 'charact..."
1,2,2020.0,"[{'name': 'American High', 'id': 112397}, {'na...",['united states of america'],NaN,NaN,0.0,2026-03-13,NaN,Pizza Movie,...,NaN,NaN,College is a trip.,A group of college students go downstairs to t...,[en],"[{'id': 1653291, 'name': 'Gaten Matarazzo', 'c...",College is a trip.,A group of college students go downstairs to t...,[en],"[{'id': 1653291, 'name': 'Gaten Matarazzo', 'c..."
2,3,2020.0,"[{'name': 'Lord Miller', 'id': 77973}, {'name'...",['united states of america'],638443000.0,438443000.0,0.0,2026-03-15,200000000.0,Project Hail Mary,...,438443000.0,2.1922,Believe in the Hail Mary.,Science teacher Ryland Grace wakes up on a spa...,"[en, zh, ru]","[{'id': 30614, 'name': 'Ryan Gosling', 'charac...",Believe in the Hail Mary.,Science teacher Ryland Grace wakes up on a spa...,"[en, zh, ru]","[{'id': 30614, 'name': 'Ryan Gosling', 'charac..."
3,4,2020.0,NaN,['united states of america'],NaN,NaN,0.0,2026-02-28,NaN,The Match-Stick Flame 3: Red Mafia,...,NaN,NaN,None,"Dalton, who's now a bounty hunter, finishes hi...",[en],"[{'id': 1379504, 'name': 'Craig Robert Bruss',...",None,"Dalton, who's now a bounty hunter, finishes hi...",[en],"[{'id': 1379504, 'name': 'Craig Robert Bruss',..."
4,5,2020.0,"[{'name': 'Pixar', 'id': 3}]",['united states of america'],371329450.0,221329450.0,0.0,2026-03-04,150000000.0,Hoppers,...,221329450.0,1.4755,Act natural.,Scientists have discovered how to 'hop' human ...,"[en, es]","[{'id': 1308818, 'name': 'Piper Curda', 'chara...",Act natural.,Scientists have discovered how to 'hop' human ...,"[en, es]","[{'id': 1308818, 'name': 'Piper Curda', 'chara..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285454,292696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,How to Answer the Fool,...,NaN,NaN,A Presuppositional Defense of the Faith,"Produced as a cinematic film, How to Answer th...",[],"[{'id': 2246791, 'name': 'Sye Ten Bruggencate'...",A Presuppositional Defense of the Faith,"Produced as a cinematic film, How to Answer th...",[],"[{'id': 2246791, 'name': 'Sye Ten Bruggencate'..."
285455,292697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ghost Stories: The Curious Tales of the Making...,...,NaN,NaN,None,An all-new 72 minute featurette including inte...,[],"[{'id': 1173259, 'name': 'Kim Newman', 'charac...",None,An all-new 72 minute featurette including inte...,[],"[{'id': 1173259, 'name': 'Kim Newman', 'charac..."
285456,292698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phantasmagorical Mystery Tour,...,NaN,NaN,None,Phantasmagorical Mystery Tour – location tour ...,[],"[{'id': 97939, 'name': 'Reggie Bannister', 'ch...",None,Phantasmagorical Mystery Tour – location tour ...,[],"[{'id': 97939, 'name': 'Reggie Bannister', 'ch..."
285457,292699,NaN,"[{'name': 'Boll KG', 'id': 15127}]","['canada', 'germany', 'united states of america']",NaN,NaN,NaN,NaN,NaN,Rampage IV: The New Blood,...,NaN,NaN,None,The fourth film in the Bill Williamson saga.,[en],"[{'id': 32205, 'name': 'Brendan Fletcher', 'ch...",None,The fourth film in the Bill Williamson saga.,[en],"[{'id': 32205, 'name': 'Brendan Fletcher', 'ch..."
285458,292700,NaN,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",['united states of america'],NaN,NaN,NaN,NaN,NaN,Hunchback,...,NaN,NaN,None,Live-action adaptation of Disney's animated mu...,[en],[],None,Live-action adaptation of Disney's animated mu...,[en],[]

In [46]:
# Verify no rows were lost
files = split_df_to_csvs(df_new, max_mb=95, base_name="final_tmdb_data")

total_rows = sum(len(pd.read_csv(f)) for f in files)
print(f"Original: {len(df_new)} rows")
print(f"In CSVs:  {total_rows} rows")
print(f"Lost:     {len(df_new) - total_rows} rows")

  Written: final_tmdb_data_1_of_14.csv (22392 rows)
  Written: final_tmdb_data_2_of_14.csv (22392 rows)
  Written: final_tmdb_data_3_of_14.csv (22392 rows)
  Written: final_tmdb_data_4_of_14.csv (22392 rows)
  Written: final_tmdb_data_5_of_14.csv (22392 rows)
  Written: final_tmdb_data_6_of_14.csv (22392 rows)
  Written: final_tmdb_data_7_of_14.csv (22392 rows)
  Written: final_tmdb_data_8_of_14.csv (22392 rows)
  Written: final_tmdb_data_9_of_14.csv (22392 rows)
  Written: final_tmdb_data_10_of_14.csv (22392 rows)
  Written: final_tmdb_data_11_of_14.csv (22392 rows)
  Written: final_tmdb_data_12_of_14.csv (22392 rows)
  Written: final_tmdb_data_13_of_14.csv (22392 rows)
  Written: final_tmdb_data_14_of_14.csv (1604 rows)
Original: 292700 rows
In CSVs:  292700 rows
Lost:     0 rows